version: '3.9'

services:
  # DB Service
  db:
    image: mysql:5.7
    container_name: student_db
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: student_db1
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Flask API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-crud-api
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      DATABASE_URI: mysql+pymysql://root:Admin%40123@db:3306/student_db1
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0"]

# Volumes
volumes:
  db_data:

# Networks
networks:
  app-network:
    driver: bridge
